In [13]:
import pandas as pd

In [14]:
df=pd.read_csv("CSV/cereals.csv")

In [15]:
print(df)

                        name  calories  protein  vitamins     rating
0                  100% Bran        70        4        25  68.402973
1          100% Natural Bran       120        3         0  33.983679
2                   All-Bran        70        4        25  59.425505
3  All-Bran with Extra Fiber        50        4        25  93.704912
4             Almond Delight       110        2        25  34.384843
5    Apple Cinnamon Cheerios       110        2        25  29.509541
6                Apple Jacks       110        2        25  33.174094
7                    Basic 4       130        3        25  37.038562
8                  Bran Chex        90        2        25  49.120253
9                Bran Flakes        90        3        25  53.313813

In [16]:
ascdf=df.sort_values(by="rating")

In [17]:
descdf=df.sort_values(by="rating",ascending=False)

In [18]:
pd.concat([ascdf,descdf],axis=1)

,name,calories,protein,vitamins,rating,name,calories,protein,vitamins,rating
5,Apple Cinnamon Cheerios,110,2,25,29.509541,Apple Cinnamon Cheerios,110,2,25,29.509541
6,Apple Jacks,110,2,25,33.174094,Apple Jacks,110,2,25,33.174094
1,100% Natural Bran,120,3,0,33.983679,100% Natural Bran,120,3,0,33.983679
4,Almond Delight,110,2,25,34.384843,Almond Delight,110,2,25,34.384843
7,Basic 4,130,3,25,37.038562,Basic 4,130,3,25,37.038562
8,Bran Chex,90,2,25,49.120253,Bran Chex,90,2,25,49.120253
9,Bran Flakes,90,3,25,53.313813,Bran Flakes,90,3,25,53.313813
2,All-Bran,70,4,25,59.425505,All-Bran,70,4,25,59.425505
0,100% Bran,70,4,25,68.402973,100% Bran,70,4,25,68.402973
3,All-Bran with Extra Fiber,50,4,25,93.704912,All-Bran with Extra Fiber,50,4,25,93.704912

In [19]:
pd.concat([ascdf,descdf],axis=0)

                        name  calories  protein  vitamins     rating
5    Apple Cinnamon Cheerios       110        2        25  29.509541
6                Apple Jacks       110        2        25  33.174094
1          100% Natural Bran       120        3         0  33.983679
4             Almond Delight       110        2        25  34.384843
7                    Basic 4       130        3        25  37.038562
8                  Bran Chex        90        2        25  49.120253
9                Bran Flakes        90        3        25  53.313813
2                   All-Bran        70        4        25  59.425505
0                  100% Bran        70        4        25  68.402973
3  All-Bran with Extra Fiber        50        4        25  93.704912
3  All-Bran with Extra Fiber        50        4        25  93.704912
0                  100% Bran        70        4        25  68.402973
2                   All-Bran        70        4        25  59.425505
9                Bran Flakes        90        3        25  53.313813
8                  Bran Chex        90        2        25  49.120253
7                    Basic 4       130        3        25  37.038562
4             Almond Delight       110        2        25  34.384843
1          100% Natural Bran       120        3         0  33.983679
6                Apple Jacks       110        2        25  33.174094
5    Apple Cinnamon Cheerios       110        2        25  29.509541